language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.3
          dist: precise
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.1
          env: DEPENDENCIES=dev SYMFONY_DEPRECATIONS_HELPER=weak
    allow_failures:
        - php: hhvm
        - php: nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script: phpunit --version

script: phpunit -v --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
