language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.1
          env: DEPENDENCIES=dev SYMFONY_DEPRECATIONS_HELPER=weak
    allow_failures:
        - php: nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install: composer update --prefer-dist $COMPOSER_FLAGS

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
